### ISSUE TITLE
Maps APIサンプルコードについてのIMO:sweet_potato:

### ISSUE THREAD

**Issue by mochi5o** [taroosg/gs_dev_samples#1]
https://github.com/taroosg/gs_dev_samples/blob/main/05_js04_api.pdf

上記資料のp.54のピンの生成以降の、マップの中心を取得するコードについての共有:raising_hand:
（同様の記述があるp.59なども同じ。）

https://mapapi.org/open.php?file=example05&h=2
このあたりのサンプルコード見ていて、ちょいシンプルにかけるなと思ったのでシェアしておきます:sweet_potato:

```js
function pushPin(map){
	let location = map.getCenter();  // こういう書き方でマップオブジェクトの持つ中心座標を取得可能
	let pin = new Microsoft.Maps.Pushpin(location, {
		color: 'navy',
		visible: true,
	});
	map.entities.push(pin);
}

function mapsInit(position){
	const lat = position.coords.latitude;
	const lng = position.coords.longitude;
	map = new Microsoft.Maps.Map('#map', {
		center: {
			latitude: lat,
			longitude: lng,
		},
		zoom: 15,
	});
	pushPin(map);
}
```

**Comment by taroosg** [comment]
ピン生成は「ピン立てたい座標」を入力して「ピン立てる」関数にしたほうが汎用性高そうかなーという感じでこのようなコードになってます（本当は戻り値なしの関数はつくりたくないけど受講生が沼るので↑の状態）．

`map.getCenter();`はじめて知ったけどこれはこれで便利そう
